src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $edited_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Subject $subject = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getEditedAt(): ?\DateTimeImmutable
    {
        return $this->edited_at;
    }

    public function setEditedAt(\DateTimeImmutable $edited_at): self
    {
        $this->edited_at = $edited_at;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Subject.php
<?php

namespace App\Entity;

use App\Repository\SubjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubjectRepository::class)]
class Subject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?bool $is_open = true;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'subjects')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'subject', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: Tag::class, mappedBy: 'subject', cascade: ['persist'])]
    private Collection $tags;

    #[ORM\ManyToMany(targetEntity: Vote::class, mappedBy: 'subject')]
    private Collection $votes;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function isIsOpen(): ?bool
    {
        return $this->is_open;
    }

    public function setIsOpen(bool $is_open): self
    {
        $this->is_open = $is_open;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setSubject($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getSubject() === $this) {
                $comment->setSubject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
            $tag->addSubject($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeSubject($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->addSubject($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->removeElement($vote)) {
            $vote->removeSubject($this);
        }

        return $this;
    }
}

src/Entity/Vote.php
<?php

namespace App\Entity;

use App\Repository\VoteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoteRepository::class)]
class Vote
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $is_up = null;

    #[ORM\ManyToOne(inversedBy: 'votes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Subject::class, inversedBy: 'votes')]
    private Collection $subject;

    public function __construct()
    {
        $this->subject = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isIsUp(): ?bool
    {
        return $this->is_up;
    }

    public function setIsUp(bool $is_up): self
    {
        $this->is_up = $is_up;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Subject>
     */
    public function getSubject(): Collection
    {
        return $this->subject;
    }

    public function addSubject(Subject $subject): self
    {
        if (!$this->subject->contains($subject)) {
            $this->subject->add($subject);
        }

        return $this;
    }

    public function removeSubject(Subject $subject): self
    {
        $this->subject->removeElement($subject);

        return $this;
    }
}

src/Form/SubjectType.php
<?php

namespace App\Form;

use App\Entity\Subject;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubjectType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'attr' => [
                    'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
                ],
                'label_attr' => [
                    'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
                ]
            ])
            ->add('use_tags', EntityType::class, [
                'class' => Tag::class,
                'choice_label' => function ($tag) {
                    return "#".$tag->getName();
                },
                'attr' => [
                    'class' => 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline flex flex-wrap gap-2'
                ],
                'label_attr' => [
                    'class' => "mt-2 block text-gray-700 text-sm font-bold mb-2"
                ],
                'placeholder' => 'Choisissez des tags',
                'multiple' => true,
                'expanded' => true,
                'mapped' => false
            ])
            ->add('tags', CollectionType::class, [
                'label' => false,
                'entry_type' => TagType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('comment', CommentType::class, [
                'label' => false,
                'mapped' => false
            ])
            ->add('Enregistrer', SubmitType::class, [
                'attr' => [
                    'class' => 'bg-amber-500 hover:bg-amber-700 text-white font-bold mt-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Subject::class,
        ]);
    }
}

src/Controller/SubjectController.php
<?php

namespace App\Controller;

use DateTimeZone;
use App\Entity\Tag;
use App\Entity\Comment;
use App\Entity\Subject;
use App\Entity\Vote;
use App\Form\CommentType;
use App\Form\SubjectType;
use App\Form\VoteType;
use App\Repository\CommentRepository;
use App\Repository\TagRepository;
use App\Repository\SubjectRepository;
use App\Repository\VoteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SubjectController extends AbstractController
{
    private $entityManager;
    private $repo;
    private $voteRepo;
    private $commentRepo;

    public function __construct(EntityManagerInterface $entityManager, SubjectRepository $repo, VoteRepository $voteRepo, CommentRepository $commentRepo)
    {
        $this->entityManager = $entityManager;
        $this->repo = $repo;
        $this->voteRepo = $voteRepo;
        $this->commentRepo = $commentRepo;
    }

    #[Route('/subject/new', name: 'app_subject_new')]
    public function index(Request $request, TagRepository $tagRepo): Response
    {
        $subject = new Subject();
        $comment = new Comment();

        $form = $this->createForm(SubjectType::class, $subject);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $subject->setCreatedAt(new \DateTimeImmutable('now'), new DateTimeZone('Europe/Paris'));
            $subject->setUser($this->getUser());

            if (isset($request->get('subject')['use_tags'])) {
                foreach ($request->get('subject')['use_tags'] as $useTag) {
                    $subject->addTag($tagRepo->find($useTag));
                }
            }

            $comment->setContent($request->get('subject')['comment']['content']);
            $comment->setCreatedAt(new \DateTimeImmutable('now'), new DateTimeZone('Europe/Paris'));
            $comment->setEditedAt(new \DateTimeImmutable('now'), new DateTimeZone('Europe/Paris'));
            $comment->setUser($this->getUser());

            $subject->addComment($comment);

            $this->entityManager->persist($subject);
            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            if (isset($request->get('subject')['tags'])) {
                foreach ($request->get('subject')['tags'] as $tag) {

                    $newTag = $tagRepo->findByName($tag['name']);
                    $newTag->addSubject($subject);
                    
                    $this->entityManager->persist($newTag);
                }
            }

            $this->entityManager->flush();

            return $this->redirectToRoute('app_subject', ['id' => $subject->getId()]);
        }

        return $this->render('subject/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/subject/{id}', name: 'app_subject')]
    public function show(Subject $subject, Request $request)
    {
        
        $vote = new Vote();

        $voteForm = $this->createform(VoteType::class, $vote);
        $voteForm->handleRequest($request);

        if ($voteForm->isSubmitted() && $voteForm->isValid()) {
            
            if ($voteForm->get('upVote')->getName() === 'upVote') {
                $vote->setIsUp(true); 
            }  elseif ($voteForm->get('downVote')->getName() === 'downVote') {
                $vote->setIsUp(false);
            }

            $vote->setUser($this->getUser());
            $subject->addVote($vote);
            
            $this->entityManager->persist($subject);
            $this->entityManager->persist($vote);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_subject', ['id' => $subject->getId()]);
        }
        
        $comment = new Comment();
        $commentForm = $this->createform(CommentType::class, $comment);
        $commentForm->handleRequest($request);

        if ($commentForm->isSubmitted() && $commentForm->isValid()) {

            $comment->setCreatedAt(new \DateTimeImmutable('now'), new DateTimeZone('Europe/Paris'));
            $comment->setEditedAt(new \DateTimeImmutable('now'), new DateTimeZone('Europe/Paris'));
            $comment->setUser($this->getUser());

            $subject->addComment($comment);

            $this->entityManager->persist($subject);
            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_subject', ['id' => $subject->getId()]);
        }

        return $this->render('subject/show.html.twig', [
            'subject' => $subject,
            'commentForm' => $commentForm->createView(),
            'voteForm' => $voteForm->createView()
        ]);
    }
}

templates/subject/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forum | New Subject
{% endblock %}

{% block body %}

	<h1 class="text-2xl font-bold text-center mb-2">Nouveau topic</h1>

	{{ form_start(form) }}
	{{ form_row(form.title) }}
	{{ form_row(form.use_tags) }}

	<h3 class="mt-2 block text-gray-700 text-sm font-bold mb-2">Tags</h3>

	<ul class="tags" data-index="{{ form.tags|length > 0 ? form.tags|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(form.tags.vars.prototype)|e('html_attr') }}"></ul>

	<button type="button" class="add_item_link bg-amber-500 hover:bg-amber-700 text-white font-bold mt-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline" data-collection-holder-class="tags">Add a tag</button>

	{# <h3>Premier commentaire</h3> #}
	{# {{ form_row(form.comment.content) }} #}


	{{ form_end(form) }}


{% endblock %}

{% block script %}
	<script>
		window.addEventListener("DOMContentLoaded", () => {

        const addTagFormDeleteLink = (item) => {
            const removeFormButton = document.createElement('button');
            removeFormButton.innerText = 'Delete this tag';
            removeFormButton.classList.add('bg-red-500','hover:bg-red-700','text-white','font-bold','mt-2','py-2','px-4','rounded','focus:outline-none','focus:shadow-outline')


            item.append(removeFormButton);

            removeFormButton.addEventListener('click', (e) => {
                e.preventDefault();
                // remove the li for the tag form
                item.remove();
            });
        }

        

        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

            const item = document.createElement('li');

            item.innerHTML = collectionHolder.dataset.prototype.replace(/__name__/g, collectionHolder.dataset.index);

            collectionHolder.appendChild(item);

            collectionHolder.dataset.index ++;

            addTagFormDeleteLink(item);

        };

        document.querySelectorAll('.add_item_link').forEach(btn => {
        btn.addEventListener("click", addFormToCollection)
        });

        })
	</script>
{% endblock %}

templates/subject/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forum | New Subject
{% endblock %}

{% block body %}

{% set upVoteCount = 0 %}
{% set downVoteCount = 0 %}
{% for vote in subject.votes %}
    {% if vote.isUp == true %}
        {% set upVoteCount = upVoteCount + 1 %}
    {% elseif vote.isUp == false %}
        {% set downVoteCount = downVoteCount + 1 %}
    {% endif %}
{% endfor %}

<div class="bg-white">
    <div class="flex">
        <div class="mb-10 w-11/12">
            <h1 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ subject.title }}</h1>
            <h2 class="mt-2 text-xl tracking-tight text-gray-900 sm:text-4xl">{{ subject.user.username }}</h2>
            <ul class="mt-2 flex gap-x-1">
                {% for t in subject.tags %}
                    <li>
                        <span class="inline-flex items-center rounded-full bg-gray-50 px-1.5 py-0.5 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">{{ t.name }}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="w-1/12 flex flex-col justify-center gap-y-2">
            <div class="flex gap-2">
                <div>
                    {{ form(voteForm) }}
                </div>
                <div class="self-center">
                    <p class="h-7">{{ upVoteCount }}</p>
                    <p class="h-7">{{ downVoteCount }}</p>
                </div>
            </div>
        </div>
    </div>

    
        <div>
            <h2 class="text-lg">Commentaires</h2>
            <div class="">
                {% for c in subject.comments %}
                    <div class="flex space-x-4 text-sm text-gray-500">
                        <div class="flex-none py-5">
                            <img src="https://images.unsplash.com/photo-1502685104226-ee32379fefbe?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" alt="" class="h-10 w-10 rounded-full bg-gray-100">
                        </div>
                        <div class="flex-1 py-5">
                            <div class="flex justify-between">
                                <h3 class="font-medium text-gray-900">{{ c.user.username }}</h3>
                                {% if app.user and c.user.id == app.user.id %}
                                    <a href=' {{ url('app_comment_edit', {'comment': c.id}) }} ' class='text-indigo-500'>Modifier</a>
                                {% endif %}
                            </div>
                            <p>
                                <time datetime="2021-07-16">{{ c.createdAt == c.editedAt ? 'Créé le ' ~ c.createdAt|date('d/m/Y H:i') : 'Edité le ' ~ c.editedAt|date('d/m/Y H:i') }}</time>
                            </p>
                            <div class="prose prose-sm mt-4 max-w-none text-gray-500">
                                <p>{{ c.content }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    {{ form_start(commentForm) }}
        {{ form_row(commentForm.content) }}
        <button type="submit" class="bg-amber-500 hover:bg-amber-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Envoyer</button>
    {{ form_end(commentForm) }}
</div>


{% endblock %}

{% block script %}
	
{% endblock %}